url: "https://radiokot.com.ua" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
lang: "en"
title: "Oleg Koretsky" # the name of your site, e.g. ACME Corp.
description: "I like to solve practical problems with programming and electronics"
email: oleg@radiokot.com.ua
lightning: oleg@radiokot.com.ua

collections:
  authors:
    output: false
  projects:
    output: true
    permalink: /p/:title
    order:
      - 4money.html
      - umbrel-cloudflared.html
      - photoprism-android-gallery.html
      - ln-addr-to-invoice.html
      - bike-nav-display.html
      - physical-object-layout.html
      - hammill.html
      - voda.html
      - citatnik.html
      - feed.html
      - vkdocs.html
      - likechecker.html

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      background_color: "white"
      has_background_image: true
      author: "oleg"
      is_dead: false

exclude:
  - "README.md"
  - "start_dev.sh"
