url: "https://radiokot.com.ua" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Олег Корецкий" # the name of your site, e.g. ACME Corp.
description: "Я люблю решать практические задачи с помощью программирования и электроники"

collections:
  authors:
  projects:
    output: true
    permalink: /p/:title
    order:
      - bike-nav-display.html
      - voda.html
      - physical-object-layout.html
      - citatnik.html
      - feed.html
      - hammill.html
      - vkdocs.html
      - likechecker.html

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      background_color: "white"
      has_background_image: true
      has_footer_image: true
      author: "oleg"
      is_dead: false

exclude:
  - "README.md"
  - "start_dev.sh"