url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Олег Корецкий" # the name of your site, e.g. ACME Corp.

collections:
  projects:
    output: true
    permalink: /p/:title

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      background_color: "white"
      has_background_image: true