name: Build and deploy the website

on:
  push:
    branches: ["main"]
    paths-ignore:
      - 'README.md'
      - 'start_dev.sh'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build the site
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

      - name: Upload the build
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: _site/

  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: DO
      url: ${{ vars.PUBLIC_URL }}
    needs: build

    steps:
      - name: Download the build
        uses: actions/download-artifact@v3
        with:
          name: site

      - name: Rsync the build to the environment
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr
          remote_path: ${{ secrets.DEPLOYMENT_PATH }}
          remote_host: ${{ secrets.HOSTNAME }}
          remote_user: ${{ secrets.WEB_USER_NAME }}
          remote_key: ${{ secrets.WEB_USER_KEY }}

      - name: Purge Cloudflare cache
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.WEB_USER_NAME }}
          key: ${{ secrets.WEB_USER_KEY }}
          script: ./purge_cloudflare_cache.sh
